/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EthernetManager: typeof import('./src/components/ethernet/EthernetManager.vue')['default']
    EthernetTrayMenu: typeof import('./src/components/ethernet/EthernetTrayMenu.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    InterfaceCard: typeof import('./src/components/ethernet/InterfaceCard.vue')['default']
    Popup: typeof import('./src/components/popup/Popup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VApp: typeof import('vuetify/lib')['VApp']
    VAppBar: typeof import('vuetify/lib')['VAppBar']
    VBtn: typeof import('vuetify/lib')['VBtn']
    VCard: typeof import('vuetify/lib')['VCard']
    VCardActions: typeof import('vuetify/lib')['VCardActions']
    VCardSubtitle: typeof import('vuetify/lib')['VCardSubtitle']
    VCardTitle: typeof import('vuetify/lib')['VCardTitle']
    VCol: typeof import('vuetify/lib')['VCol']
    VContainer: typeof import('vuetify/lib')['VContainer']
    VExpansionPanel: typeof import('vuetify/lib')['VExpansionPanel']
    VExpansionPanelContent: typeof import('vuetify/lib')['VExpansionPanelContent']
    VExpansionPanelHeader: typeof import('vuetify/lib')['VExpansionPanelHeader']
    VExpansionPanels: typeof import('vuetify/lib')['VExpansionPanels']
    VIcon: typeof import('vuetify/lib')['VIcon']
    VMenu: typeof import('vuetify/lib')['VMenu']
    VOverlay: typeof import('vuetify/lib')['VOverlay']
    VRow: typeof import('vuetify/lib')['VRow']
    VSpacer: typeof import('vuetify/lib')['VSpacer']
  }
}
